name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Cambia a 'master' si usas esa rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Puedes usar la versión de Node que prefieras, 20 es estable

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # La carpeta que genera Vite
        # Añade la siguiente línea si usas React Router DOM (para evitar la pantalla en blanco inicial)
        # cname: your-custom-domain.com # Descomentar si usas un dominio personalizado
